Netplan update
rackn/netwrangler pull request #16
Opened 2021-08-02 20:10 UTC by mediamagnet

Added dhcp-overrides for ipv4 and v6.

2021-08-02 20:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rackn/netwrangler?pullRequest=16) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rackn/netwrangler?pullRequest=16) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rackn/netwrangler?pullRequest=16) it.</sub>

2021-08-02 21:23 UTC, VictorLowther requested changes
This also needs matching code in the RHEL and systemd directories, to the extent that those network config formats can handle these settings.

2021-08-02 21:23 UTC, VictorLowther commented on test-data/dhcp-override/internal/expect
> +        use-routes: true
I would not emit values under dhcp4-overrides that are at whatever the netplan spec says should be the defaults.

2021-08-02 21:23 UTC, VictorLowther commented on test-data/dhcp/netplan.yaml
> +      dhcp4: true
Format here needs to not change.

2021-08-02 21:23 UTC, VictorLowther commented on util/layout.go
> +
Same here.

2021-08-02 21:23 UTC, VictorLowther commented on util/layout.go
> +	UseDomains      string  `json:"use-domains,omitempty"`
Since the defaults for these are not the zero values, omitempty should probably not be present and you may need custom marshal/unmarshal code

2021-08-12 20:43 UTC, mediamagnet commented
Should be all updated in 95eec95342152d977ae2fb9dce83ac8b26196c25

2021-08-13 17:52 UTC, merged